repos:
  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
        exclude: "{{cookiecutter.app_name}}"
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: "{{cookiecutter.app_name}}"
